version: '3.8'

services:
  laravel-app:
    image: edgeforge-labs/laravel-app:latest
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Maps port 8080 on host to port 80 in the container for nginx
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - ./:/var/www  # Mounts the current directory to /var/www inside the container
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"  # Exposes MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for MySQL data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
